### ISSUE TITLE
can't find crate for `holochain_core_types_derive`

### ISSUE THREAD

**Issue by marcusnewton** [willemolding/holochain-rust-todo#5]
hc package aborting

**Comment by marcusnewton** [comment]
manual fix by adding `holochain_core_types_derive = { git = "https://github.com/holochain/holochain-rust" , branch = "master" }` to dependencies in Cargo.toml

**Comment by doronaviguy** [comment]
I suggest to add this to the medium blog post ,
so the tutorial would be perfect
